spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

  mail:
    username: ${SUPPORT_EMAIL}
    password: ${APP_PASSWORD}

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  config:
    import: optional:file:.env[.properties]

server:
  port: 5000
  servlet:
    context-path: /api/v1

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 3600000 # 1 hora